# Usa la imagen oficial de MongoDB 8.0
FROM mongo:8.0

# Configura el puerto por defecto de MongoDB
EXPOSE 27017

# Crea un volumen para persistencia de datos
VOLUME /data/db

# Comando de inicio para MongoDB
CMD ["mongod"]

