version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"           # Expone el puerto al host (Compass funcionará)
    volumes:
      - mongo_data:/data/db     # Volumen para persistencia
    restart: unless-stopped     # Se reinicia automáticamente al encender el sistema

volumes:
  mongo_data:

